name: welfog
description: Welfog main Flutter app
publish_to: "none"
version: 1.2.0+64

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  welfog_flutter_play:
    path: ./flutter_play_module
  http: ^1.2.0
  shared_preferences: ^2.3.5
  flutter_svg: ^2.3.0
  share_plus: ^10.1.4
  webview_flutter: ^4.10.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vector/
    - assets/icons/login/
