/// Canonical WELFOG play share URLs (used by Flutter reels + profile share).
class ShareLinks {
  static const _apiHost = 'https://api.welfog.com';

  /// Video share link — backend expects full 24-char reel id + numeric sharer userid.
  static String playReelUrl(String reelId, String sharerUserId) {
    return '$_apiHost/api/plays/r/$reelId-$sharerUserId';
  }

  /// Profile share links are generated by GET /plays/profile/{mongoId}/share.
  /// Opening uses the returned /api/plays/p/{slug} short link.
  static String playProfileUrl(String slug) {
    return '$_apiHost/api/plays/p/$slug';
  }
}
